package learning

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i hw4/internal/learning.TutorServiceApi -o ./tutor_service_api_mock_test.go -n TutorServiceApiMock

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// TutorServiceApiMock implements TutorServiceApi
type TutorServiceApiMock struct {
	t minimock.Tester

	funcSubjects          func() (sa1 []string)
	inspectFuncSubjects   func()
	afterSubjectsCounter  uint64
	beforeSubjectsCounter uint64
	SubjectsMock          mTutorServiceApiMockSubjects

	funcTutorsID          func(subject string) (ia1 []int64)
	inspectFuncTutorsID   func(subject string)
	afterTutorsIDCounter  uint64
	beforeTutorsIDCounter uint64
	TutorsIDMock          mTutorServiceApiMockTutorsID
}

// NewTutorServiceApiMock returns a mock for TutorServiceApi
func NewTutorServiceApiMock(t minimock.Tester) *TutorServiceApiMock {
	m := &TutorServiceApiMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SubjectsMock = mTutorServiceApiMockSubjects{mock: m}

	m.TutorsIDMock = mTutorServiceApiMockTutorsID{mock: m}
	m.TutorsIDMock.callArgs = []*TutorServiceApiMockTutorsIDParams{}

	return m
}

type mTutorServiceApiMockSubjects struct {
	mock               *TutorServiceApiMock
	defaultExpectation *TutorServiceApiMockSubjectsExpectation
	expectations       []*TutorServiceApiMockSubjectsExpectation
}

// TutorServiceApiMockSubjectsExpectation specifies expectation struct of the TutorServiceApi.Subjects
type TutorServiceApiMockSubjectsExpectation struct {
	mock *TutorServiceApiMock

	results *TutorServiceApiMockSubjectsResults
	Counter uint64
}

// TutorServiceApiMockSubjectsResults contains results of the TutorServiceApi.Subjects
type TutorServiceApiMockSubjectsResults struct {
	sa1 []string
}

// Expect sets up expected params for TutorServiceApi.Subjects
func (mmSubjects *mTutorServiceApiMockSubjects) Expect() *mTutorServiceApiMockSubjects {
	if mmSubjects.mock.funcSubjects != nil {
		mmSubjects.mock.t.Fatalf("TutorServiceApiMock.Subjects mock is already set by Set")
	}

	if mmSubjects.defaultExpectation == nil {
		mmSubjects.defaultExpectation = &TutorServiceApiMockSubjectsExpectation{}
	}

	return mmSubjects
}

// Inspect accepts an inspector function that has same arguments as the TutorServiceApi.Subjects
func (mmSubjects *mTutorServiceApiMockSubjects) Inspect(f func()) *mTutorServiceApiMockSubjects {
	if mmSubjects.mock.inspectFuncSubjects != nil {
		mmSubjects.mock.t.Fatalf("Inspect function is already set for TutorServiceApiMock.Subjects")
	}

	mmSubjects.mock.inspectFuncSubjects = f

	return mmSubjects
}

// Return sets up results that will be returned by TutorServiceApi.Subjects
func (mmSubjects *mTutorServiceApiMockSubjects) Return(sa1 []string) *TutorServiceApiMock {
	if mmSubjects.mock.funcSubjects != nil {
		mmSubjects.mock.t.Fatalf("TutorServiceApiMock.Subjects mock is already set by Set")
	}

	if mmSubjects.defaultExpectation == nil {
		mmSubjects.defaultExpectation = &TutorServiceApiMockSubjectsExpectation{mock: mmSubjects.mock}
	}
	mmSubjects.defaultExpectation.results = &TutorServiceApiMockSubjectsResults{sa1}
	return mmSubjects.mock
}

// Set uses given function f to mock the TutorServiceApi.Subjects method
func (mmSubjects *mTutorServiceApiMockSubjects) Set(f func() (sa1 []string)) *TutorServiceApiMock {
	if mmSubjects.defaultExpectation != nil {
		mmSubjects.mock.t.Fatalf("Default expectation is already set for the TutorServiceApi.Subjects method")
	}

	if len(mmSubjects.expectations) > 0 {
		mmSubjects.mock.t.Fatalf("Some expectations are already set for the TutorServiceApi.Subjects method")
	}

	mmSubjects.mock.funcSubjects = f
	return mmSubjects.mock
}

// Subjects implements TutorServiceApi
func (mmSubjects *TutorServiceApiMock) Subjects() (sa1 []string) {
	mm_atomic.AddUint64(&mmSubjects.beforeSubjectsCounter, 1)
	defer mm_atomic.AddUint64(&mmSubjects.afterSubjectsCounter, 1)

	if mmSubjects.inspectFuncSubjects != nil {
		mmSubjects.inspectFuncSubjects()
	}

	if mmSubjects.SubjectsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSubjects.SubjectsMock.defaultExpectation.Counter, 1)

		mm_results := mmSubjects.SubjectsMock.defaultExpectation.results
		if mm_results == nil {
			mmSubjects.t.Fatal("No results are set for the TutorServiceApiMock.Subjects")
		}
		return (*mm_results).sa1
	}
	if mmSubjects.funcSubjects != nil {
		return mmSubjects.funcSubjects()
	}
	mmSubjects.t.Fatalf("Unexpected call to TutorServiceApiMock.Subjects.")
	return
}

// SubjectsAfterCounter returns a count of finished TutorServiceApiMock.Subjects invocations
func (mmSubjects *TutorServiceApiMock) SubjectsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSubjects.afterSubjectsCounter)
}

// SubjectsBeforeCounter returns a count of TutorServiceApiMock.Subjects invocations
func (mmSubjects *TutorServiceApiMock) SubjectsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSubjects.beforeSubjectsCounter)
}

// MinimockSubjectsDone returns true if the count of the Subjects invocations corresponds
// the number of defined expectations
func (m *TutorServiceApiMock) MinimockSubjectsDone() bool {
	for _, e := range m.SubjectsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SubjectsMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSubjectsCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSubjects != nil && mm_atomic.LoadUint64(&m.afterSubjectsCounter) < 1 {
		return false
	}
	return true
}

// MinimockSubjectsInspect logs each unmet expectation
func (m *TutorServiceApiMock) MinimockSubjectsInspect() {
	for _, e := range m.SubjectsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to TutorServiceApiMock.Subjects")
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SubjectsMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSubjectsCounter) < 1 {
		m.t.Error("Expected call to TutorServiceApiMock.Subjects")
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSubjects != nil && mm_atomic.LoadUint64(&m.afterSubjectsCounter) < 1 {
		m.t.Error("Expected call to TutorServiceApiMock.Subjects")
	}
}

type mTutorServiceApiMockTutorsID struct {
	mock               *TutorServiceApiMock
	defaultExpectation *TutorServiceApiMockTutorsIDExpectation
	expectations       []*TutorServiceApiMockTutorsIDExpectation

	callArgs []*TutorServiceApiMockTutorsIDParams
	mutex    sync.RWMutex
}

// TutorServiceApiMockTutorsIDExpectation specifies expectation struct of the TutorServiceApi.TutorsID
type TutorServiceApiMockTutorsIDExpectation struct {
	mock    *TutorServiceApiMock
	params  *TutorServiceApiMockTutorsIDParams
	results *TutorServiceApiMockTutorsIDResults
	Counter uint64
}

// TutorServiceApiMockTutorsIDParams contains parameters of the TutorServiceApi.TutorsID
type TutorServiceApiMockTutorsIDParams struct {
	subject string
}

// TutorServiceApiMockTutorsIDResults contains results of the TutorServiceApi.TutorsID
type TutorServiceApiMockTutorsIDResults struct {
	ia1 []int64
}

// Expect sets up expected params for TutorServiceApi.TutorsID
func (mmTutorsID *mTutorServiceApiMockTutorsID) Expect(subject string) *mTutorServiceApiMockTutorsID {
	if mmTutorsID.mock.funcTutorsID != nil {
		mmTutorsID.mock.t.Fatalf("TutorServiceApiMock.TutorsID mock is already set by Set")
	}

	if mmTutorsID.defaultExpectation == nil {
		mmTutorsID.defaultExpectation = &TutorServiceApiMockTutorsIDExpectation{}
	}

	mmTutorsID.defaultExpectation.params = &TutorServiceApiMockTutorsIDParams{subject}
	for _, e := range mmTutorsID.expectations {
		if minimock.Equal(e.params, mmTutorsID.defaultExpectation.params) {
			mmTutorsID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmTutorsID.defaultExpectation.params)
		}
	}

	return mmTutorsID
}

// Inspect accepts an inspector function that has same arguments as the TutorServiceApi.TutorsID
func (mmTutorsID *mTutorServiceApiMockTutorsID) Inspect(f func(subject string)) *mTutorServiceApiMockTutorsID {
	if mmTutorsID.mock.inspectFuncTutorsID != nil {
		mmTutorsID.mock.t.Fatalf("Inspect function is already set for TutorServiceApiMock.TutorsID")
	}

	mmTutorsID.mock.inspectFuncTutorsID = f

	return mmTutorsID
}

// Return sets up results that will be returned by TutorServiceApi.TutorsID
func (mmTutorsID *mTutorServiceApiMockTutorsID) Return(ia1 []int64) *TutorServiceApiMock {
	if mmTutorsID.mock.funcTutorsID != nil {
		mmTutorsID.mock.t.Fatalf("TutorServiceApiMock.TutorsID mock is already set by Set")
	}

	if mmTutorsID.defaultExpectation == nil {
		mmTutorsID.defaultExpectation = &TutorServiceApiMockTutorsIDExpectation{mock: mmTutorsID.mock}
	}
	mmTutorsID.defaultExpectation.results = &TutorServiceApiMockTutorsIDResults{ia1}
	return mmTutorsID.mock
}

// Set uses given function f to mock the TutorServiceApi.TutorsID method
func (mmTutorsID *mTutorServiceApiMockTutorsID) Set(f func(subject string) (ia1 []int64)) *TutorServiceApiMock {
	if mmTutorsID.defaultExpectation != nil {
		mmTutorsID.mock.t.Fatalf("Default expectation is already set for the TutorServiceApi.TutorsID method")
	}

	if len(mmTutorsID.expectations) > 0 {
		mmTutorsID.mock.t.Fatalf("Some expectations are already set for the TutorServiceApi.TutorsID method")
	}

	mmTutorsID.mock.funcTutorsID = f
	return mmTutorsID.mock
}

// When sets expectation for the TutorServiceApi.TutorsID which will trigger the result defined by the following
// Then helper
func (mmTutorsID *mTutorServiceApiMockTutorsID) When(subject string) *TutorServiceApiMockTutorsIDExpectation {
	if mmTutorsID.mock.funcTutorsID != nil {
		mmTutorsID.mock.t.Fatalf("TutorServiceApiMock.TutorsID mock is already set by Set")
	}

	expectation := &TutorServiceApiMockTutorsIDExpectation{
		mock:   mmTutorsID.mock,
		params: &TutorServiceApiMockTutorsIDParams{subject},
	}
	mmTutorsID.expectations = append(mmTutorsID.expectations, expectation)
	return expectation
}

// Then sets up TutorServiceApi.TutorsID return parameters for the expectation previously defined by the When method
func (e *TutorServiceApiMockTutorsIDExpectation) Then(ia1 []int64) *TutorServiceApiMock {
	e.results = &TutorServiceApiMockTutorsIDResults{ia1}
	return e.mock
}

// TutorsID implements TutorServiceApi
func (mmTutorsID *TutorServiceApiMock) TutorsID(subject string) (ia1 []int64) {
	mm_atomic.AddUint64(&mmTutorsID.beforeTutorsIDCounter, 1)
	defer mm_atomic.AddUint64(&mmTutorsID.afterTutorsIDCounter, 1)

	if mmTutorsID.inspectFuncTutorsID != nil {
		mmTutorsID.inspectFuncTutorsID(subject)
	}

	mm_params := &TutorServiceApiMockTutorsIDParams{subject}

	// Record call args
	mmTutorsID.TutorsIDMock.mutex.Lock()
	mmTutorsID.TutorsIDMock.callArgs = append(mmTutorsID.TutorsIDMock.callArgs, mm_params)
	mmTutorsID.TutorsIDMock.mutex.Unlock()

	for _, e := range mmTutorsID.TutorsIDMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ia1
		}
	}

	if mmTutorsID.TutorsIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmTutorsID.TutorsIDMock.defaultExpectation.Counter, 1)
		mm_want := mmTutorsID.TutorsIDMock.defaultExpectation.params
		mm_got := TutorServiceApiMockTutorsIDParams{subject}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmTutorsID.t.Errorf("TutorServiceApiMock.TutorsID got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmTutorsID.TutorsIDMock.defaultExpectation.results
		if mm_results == nil {
			mmTutorsID.t.Fatal("No results are set for the TutorServiceApiMock.TutorsID")
		}
		return (*mm_results).ia1
	}
	if mmTutorsID.funcTutorsID != nil {
		return mmTutorsID.funcTutorsID(subject)
	}
	mmTutorsID.t.Fatalf("Unexpected call to TutorServiceApiMock.TutorsID. %v", subject)
	return
}

// TutorsIDAfterCounter returns a count of finished TutorServiceApiMock.TutorsID invocations
func (mmTutorsID *TutorServiceApiMock) TutorsIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmTutorsID.afterTutorsIDCounter)
}

// TutorsIDBeforeCounter returns a count of TutorServiceApiMock.TutorsID invocations
func (mmTutorsID *TutorServiceApiMock) TutorsIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmTutorsID.beforeTutorsIDCounter)
}

// Calls returns a list of arguments used in each call to TutorServiceApiMock.TutorsID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmTutorsID *mTutorServiceApiMockTutorsID) Calls() []*TutorServiceApiMockTutorsIDParams {
	mmTutorsID.mutex.RLock()

	argCopy := make([]*TutorServiceApiMockTutorsIDParams, len(mmTutorsID.callArgs))
	copy(argCopy, mmTutorsID.callArgs)

	mmTutorsID.mutex.RUnlock()

	return argCopy
}

// MinimockTutorsIDDone returns true if the count of the TutorsID invocations corresponds
// the number of defined expectations
func (m *TutorServiceApiMock) MinimockTutorsIDDone() bool {
	for _, e := range m.TutorsIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.TutorsIDMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterTutorsIDCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcTutorsID != nil && mm_atomic.LoadUint64(&m.afterTutorsIDCounter) < 1 {
		return false
	}
	return true
}

// MinimockTutorsIDInspect logs each unmet expectation
func (m *TutorServiceApiMock) MinimockTutorsIDInspect() {
	for _, e := range m.TutorsIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to TutorServiceApiMock.TutorsID with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.TutorsIDMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterTutorsIDCounter) < 1 {
		if m.TutorsIDMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to TutorServiceApiMock.TutorsID")
		} else {
			m.t.Errorf("Expected call to TutorServiceApiMock.TutorsID with params: %#v", *m.TutorsIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcTutorsID != nil && mm_atomic.LoadUint64(&m.afterTutorsIDCounter) < 1 {
		m.t.Error("Expected call to TutorServiceApiMock.TutorsID")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *TutorServiceApiMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockSubjectsInspect()

		m.MinimockTutorsIDInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *TutorServiceApiMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *TutorServiceApiMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSubjectsDone() &&
		m.MinimockTutorsIDDone()
}
